#端口配置
server:
  port: 28080
  servlet:
    context-path: /backstage
    session:
      timeout: 3600s
    jsp:
      init-parameters:
        development: true

spring:
  application:
    name: myshopping
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  #文件上传
  servlet: 
    multipart: 
      max-file-size: 5MB
   
# MyBatis
mybatis:
  type-aliases-package: com.mutil.userful.domain
  mapperLocations: classpath:mapper/*.xml
